### ISSUE TITLE
Cant install via pip install

### ISSUE THREAD

**Issue by Ondjultomte** [haijeploeg/smx10fanctl#2]
pip install smx10fanctl
Collecting smx10fanctl
  Using cached https://files.pythonhosted.org/packages/04/42/8291d4bc5d0a2608e27d17fd68fcab2eec74e2d8c169fb6d5581a83ee635/smx10fanctl-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yPTT3F/smx10fanctl/setup.py", line 3, in <module>
        from smx10fanctl.core.version import get_version
      File "smx10fanctl/core/version.py", line 1, in <module>
        from cement.utils.version import get_version as cement_get_version
    ImportError: No module named cement.utils.version

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-yPTT3F/smx10fanctl/

**Comment by haijeploeg** [comment]
Hi,

It seems I didnt include cement as a dependency. You can try this:

```
pip install cement
pip install smx10fanctl
```

I will try to fix this in the next version.

**Comment by Ondjultomte** [comment]
thnx. That solved now I got stuck here:

➜  ~ cd /etc/systemd/system/smx10fanctl.service
➜  smx10fanctl.service git:(main) ll
total 50K
-rw-r--r-- 1 root root  275 Apr  3 15:52 CHANGELOG.md
drwxr-xr-x 5 root root    7 Apr  3 15:55 env
-rw-r--r-- 1 root root 1.1K Apr  3 15:52 LICENSE
-rw-r--r-- 1 root root  289 Apr  3 15:52 Makefile
-rw-r--r-- 1 root root  136 Apr  3 15:52 MANIFEST.in
-rw-r--r-- 1 root root 3.9K Apr  3 15:52 README.md
drwxr-xr-x 2 root root    3 Apr  3 15:52 requirements
-rw-r--r-- 1 root root    0 Apr  3 15:52 setup.cfg
-rw-r--r-- 1 root root  888 Apr  3 15:52 setup.py
drwxr-xr-x 4 root root    6 Apr  3 15:52 smx10fanctl
-rw-r--r-- 1 root root  213 Apr  3 15:52 smx10fanctl.service
➜  smx10fanctl.service git:(main) systemctl enable --now smx10fanctl
Failed to lookup unit file state: Is a directory

**Comment by Ondjultomte** [comment]
➜  ~ systemctl enable smx10fanctl.service
Failed to lookup unit file state: Is a directory
➜  ~ cat smx10fanctl.service
[Unit]
Description=smx10fanctl
After=network.target

[Service]
ExecStart=/usr/local/bin/smx10fanctl auto -s -p
Type=simple
Restart=on-failure
RestartSec=6
User=root
Group=root

[Install]
WantedBy=multi-user.target#                                                                                             ➜  ~


Its not a direcrtory ?

**Comment by haijeploeg** [comment]
Hi,

It seems that you have cloned the git repo into `/etc/systemd/system/smx10fanctl.service`. You don't have to clone this repository actually. You can remove that folder using:

```
sudo rm -r /etc/systemc/system/smx10fanctl.service
```

And install the systemd unit file with:

```
sudo curl -L https://raw.githubusercontent.com/haijeploeg/smx10fanctl/main/smx10fanctl.service -o /etc/systemd/system/smx10fanctl.service
sudo chmod 644 /etc/systemd/system/smx10fanctl.service
sudo systemctl daemon-reload
sudo systemctl enable --now smx10fanctl.service
```

Hope this helps. The reason you get this error is because `/etc/systemd/system/smx10fanctl.service` should be a file. In your situation this is a folder which contains the codebase of this project including the sytemd unit file which can be installed seperately.

Please let me know if you have any more trouble settings this up. I am happy to help :)

**Comment by Ondjultomte** [comment]
Thanx is installed now, now I just need to tweak some parameters the fans cycle fanspeed slightly  every ~5s

I set these test values with ipmitool
FAN1             | 2500.000   | RPM        | nr    | 400.000   | 600.000   | 800.000   | 1000.000  | 1500.000  | 2500.000
FAN2             | 2500.000   | RPM        | nr    | 400.000   | 600.000   | 800.000   | 1000.000  | 1500.000  | 2500.000
FAN3             | 1700.000   | RPM        | cr    | 400.000   | 600.000   | 800.000   | 900.000   | 1300.000  | 2500.000
FAN4             | 1500.000   | RPM        | cr    | 400.000   | 600.000   | 800.000   | 900.000   | 1300.000  | 2500.000
FAN5             | 500.000    | RPM        | cr    | 400.000   | 600.000   | 800.000   | 900.000   | 1300.000  | 2500.000
FANA             | 1100.000   | RPM        | nc    | 400.000   | 600.000   | 800.000   | 900.000   | 1300.000  | 2500.000
FANB             | 1700.000   | RPM        | cr    | 400.000   | 600.000   | 800.000   | 900.000   | 1300.000  | 2500.000
FANC             | 1200.000   | RPM        | nc    | 400.000   | 600.000   | 800.000   | 900.000   | 1300.000  | 2500.000

Fixed with:

FAN1             | 600.000    | RPM        | ok    | 100.000   | 200.000   | 300.000   | 2500.000  | 2600.000  | 2700.000
FAN2             | 600.000    | RPM        | ok    | 100.000   | 200.000   | 300.000   | 2600.000  | 2700.000  | 2800.000
FAN3             | 500.000    | RPM        | ok    | 100.000   | 200.000   | 300.000   | 1700.000  | 1800.000  | 1900.000
FAN4             | 400.000    | RPM        | ok    | 100.000   | 200.000   | 300.000   | 1500.000  | 1600.000  | 1700.000
FAN5             | 500.000    | RPM        | nc    | 100.000   | 100.000   | 200.000   | 500.000   | 600.000   | 700.000
FANA             | 1100.000   | RPM        | nc    | 100.000   | 200.000   | 300.000   | 900.000   | 1300.000  | 2500.000
FANB             | 1000.000   | RPM        | ok    | 100.000   | 200.000   | 300.000   | 1700.000  | 1900.000  | 2000.000
FANC             | 1100.000   | RPM        | nc    | 100.000   | 200.000   | 300.000   | 900.000   | 1300.000  | 2500.000

**Comment by haijeploeg** [comment]
Hi, sorry for the delay, I got caught up. As far as I understand everything is working fine now? :)
