### ISSUE TITLE
Works wonders on an X11 motherboard!

### ISSUE THREAD

**Issue by WouterGritter** [haijeploeg/smx10fanctl#3]
> The cli tool may or may not work on x8/x9/x11 motherboards as well. Feel free to report back to me if you have tried this.

I'm running the script on my proxmox (debian) hypervisor, and even after 4 years this script works amazingly. A couple months ago I had to install a specific version of `ipmitool` using a .deb file, though now the apt version works fine. It makes the 1U server actually bearable to sit next to!

Specifically, I'm running the script on a **SYS-5019S-MR** server, with a **X11SSH-F** motherboard.

**Comment by haijeploeg** [comment]
Hi Wouter 👋 

Sorry for the late response, I didn't saw the issue popping up in my overview. Glad everything works! I did write this tool for my supermicro self built server once, and figured maybe more people are running into the ramping fans problem. I now moved to a homelab based on a Intel NUCs for saving energy :). So I cannot test this tool anymore, but glad to hear everything is still running really smooth!

If you run into problems in the future I am happy to help!

**Comment by WouterGritter** [comment]
Awesome, thanks for merging!

I'm looking to do something similar. The yearly cost of running my homelab could easily pay the price for one (or two) high-end NUCs.... However I'm also running a Dell R720 with 8 HDDs and (though I've never needed that much storage before I had them) I now have way too much storage in use to switch to a smaller storage setup 😅
